### ISSUE TITLE
Redundante externe Abhängigkeiten in Themes vermeiden

### ISSUE THREAD

**Issue by mtrojan-ub** [bsesic/tuefind#3]
Im ixtheo2-Theme sind mehrere Dateien vorhanden, die auch schon im bootstrap3-Theme vorhanden sind. Daher sollten die Dateien aus dem ixtheo2-Theme entfernt und die entsprechenden Verweise auf das bootstrap3-Theme geändert werden. 

Beispiele:
ixtheo2/css/bootstrap.css => bootstrap3/css/vendor/bootstrap.min.css
(ggf. weitere bootstrap-plugins die z.B. unter bootstrap3/css/vendor/bootstrap oder anderen Unterverzeichnissen vorhanden sind)
ixtheo2/fonts/fontawesome... => bootstrap3/css/fonts/fontawesome...

![grafik](https://user-images.githubusercontent.com/26873381/35039334-d232bf6a-fb7d-11e7-853a-1cd55bed5038.png)

**Comment by bsesic** [comment]
Habe ich rausgenommen.
