### ISSUE TITLE
Kopierte Templates durch Symlinks ersetzen

### ISSUE THREAD

**Issue by mtrojan-ub** [bsesic/tuefind#4]
In ixtheo2/templates gibt es viele Seiten die beim Erzeugen des Themes von ixtheo kopiert wurden.
Dadurch gibt es leider Änderungen in ixtheo, die in ixtheo2 nicht ankommen.

Beispiel: 
templates/static/de/A-Z.phtml => in ixtheo wurde ein weiterer Listenpunkt eingefügt, der jetzt in ixtheo2 nicht zur Verfügung steht

Es sollte immer nur dann eine Kopie in ixtheo2 erzeugt werden, wenn hier etwas fürs neue Design angepasst werden muss (z.B. Anpassung von CSS Klassen, Einfügen von Containern o.Ä.). Die anderen Kopien sollten durch Symlinks ersetzt werden!

Hinweis zur Vererbung:
Das symlinken wäre nicht notwendig, wenn man das theme statt von bootstrap3 von ixtheo ableiten würde. Das wollen wir aber nicht, da sich dann das neue+alte CSS potenziell in die Quere kommt und wir das alte Theme ja irgendwann komplett löschen möchten. Beim Arbeiten mit Symlinks kann man so zum Tag X die Symlinks durch eine aktuelle Kopie ersetzen und dann den alten ixtheo Theme löschen, sobald dieser nicht mehr benötigt wird.

**Comment by mtrojan-ub** [comment]
falls lediglich ein "display: inline" ins template eingefügt wird sollte das lieber übers CSS file gemacht werden, als das komplette Template zu kopieren und dort nur eine Zeile anzupassen.

(Beispiel: ixtheo2/templates/search/controls/sort.phtml)

**Comment by bsesic** [comment]
Vielleicht ist es eine gute Praxis veränderte Template Dateien mit einem Kommentar im PHP Code zu versehen, sodass wir wissen dass die Datei umgeändert wurde.

Eigentlich sollte das Theme ja alle Dateien automatisch vom Muttertheme ableiten, die nicht zu finden sind.
Wir müssen also alles manuell von ixtheo ableiten, was nicht von bootstrap abgeleitet werden soll.

**Comment by mtrojan-ub** [comment]
Deine Aussage verstehe ich nicht ganz:
a) "was nicht von bootstrap abgeleitet werden soll' => unterm Strich erben wir ja sowieso alles von bootstrap3, egal ob wir von "bootstrap3", "tuefind" oder "ixtheo" erben, da "tuefind" und "ixtheo" wieder indirekt von "bootstrap3" erben, erben wir ja immer von bootstrap
b) "Eigentlich sollte das Theme ja alle Dateien automatisch vom Muttertheme ableiten, die nicht zu finden sind." => richtig, aber wir wollen ja ixtheo nicht als Muttertheme für ixtheo2, weil ixtheo bald gelöscht wird, siehe mein erster Kommentar in diesem Issue

... und wie geht's mit dem Pull request weiter?

PS: Ja klar, wenn man ein Template kopiert und darin Änderungen vornimmt, ist es natürlich immer sinnvoll per PHP oder HTML-Kommentar auf die Stelle hinzuweisen die angepasst wurde.

**Comment by bsesic** [comment]
Den Pull request habe ich am Wochenende versucht zu integrieren, da gab es
aber Probleme mit den Symlinks.
Ich werde es morgen fertig machen.


Am 22. Januar 2018 um 10:02 schrieb mtrojan-ub <notifications@github.com>:

**Comment by bsesic** [comment]
Der Pull request ist gemacht. Jetzt sollte ja alles drin sein, oder?

**Comment by mtrojan-ub** [comment]
das sieht doch schonmal gut aus :+1:
