### ISSUE TITLE
config.ini

### ISSUE THREAD

**Issue by bsesic** [bsesic/tuefind#7]
Gibt es eine Möglichkeit `ixtheo2` in der `config.ini` zu behalten, sodass es nicht immer neu eingetragen werden muss?

**Comment by mtrojan-ub** [comment]
Ich würde Dir folgendes empfehlen bzw. wir haben's bei uns wie folgt aufgesetzt:
- /usr/local/vufind/local/tuefind/instances/ixtheo kopieren nach ixtheo2
- darunter (ixtheo2/config/vufind) alle Dateien außer der config.ini ersetzen durch einen symlink auf ../../../ixtheo/config/vufind/<selber dateiname>, und ixtheo2 in deiner config.ini eintragen
- In der apache config (z.B. vufind-ixtheo.conf) das VUFIND_LOCAL_DIR hinten von ixtheo auf ixtheo2 ändern

Theoretisch könntest Du auch die apache config so anpassen dass Du über mehrere VirtualHosts (z.B. auf unterschiedlichen Ports) ixtheo und ixtheo2 parallel betreiben kannst, falls das notwendig ist.
