### ISSUE TITLE
Relative Pfade für Bilder, etc.

### ISSUE THREAD

**Issue by bsesic** [bsesic/tuefind#8]
Wie kann ich relative Pfade für assets (Bilder, etc.) mit php einfügen?

**Comment by mtrojan-ub** [comment]
Im bootstrap3 machen sie's wohl wie folgt

im Template:
`<img src="<?=$this->imageLink('dateiname')?>">`

Der versucht dann Dein Image aus ixtheo2/images/<Dateiname> zu laden.
Falls er das Image nicht findet, versucht er, das image in den übergeordneten Themes zu finden.

siehe auch:
/usr/local/vufind/module/VuFindTheme/src/VuFindTheme/View/Helper/ImageLink


... und welche "assets" meinst Du sonst konkret? Hast Du mir ein Beispiel?

**Comment by bsesic** [comment]
Für Bilder reicht es erstmal. Hat geklappt. Ich hatte mir das zwar angesehen, aber vergessen dass er /images/ schon mit lädt.
